[project]
name = "tictactoe"
version = "0.0.5"
description = "tictactoe"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame-ce>=2.5.2,<3",
    "pytest>=8.3.5",
    "pytest-mock>=3.14.0",
]
